# Generated by Django 4.2.1 on 2023-06-06 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartphoneShopAPI', '0002_alter_productfeature_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='productfeature',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['id']},
        ),
    ]
