# Generated by Django 4.2.1 on 2023-06-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartphoneShopAPI', '0004_alter_productreview_options_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
